Инкремент 14
MalyginaEkaterina/shortener pull request #14
Opened 2023-02-19 20:41 UTC by MalyginaEkaterina

2023-02-21 07:54 UTC, Barugoo commented on internal/service/delete_worker.go
> +}
Давай его тоже спрячем за интерфейс, чтобы можно было замокать в юнит-тестах

2023-02-21 08:12 UTC, Barugoo commented on internal/service/delete_worker.go
> +					time.Sleep(retryIn)
Вижу что у тебя здесь немного запуталась логика из-за чего чтение новых задач (то бишь вызов метода Delete) может заблокироваться из-за ретраев, а значит клиенты будут висеть.

Давай попробуем формализовать что у тебя должно происходить в delete worker: у тебя есть буффер урлов на удаление, в который попадают задачи из эндпоинта на удаление урлов. Очистка этого буффера (то бишь выполнение Delete в базе для всех урлов в нем) выполняются в двух случаях:
- Если буффер заполнился
- Если подошло время выполнения
Эти кейсы + ctx.Done мы должны описать отдельными case-ветками внутри `select`

А затем отдельно описать логику непосредственно удаления, куда ты и положишь ретраи. Таким образом у тебя отдельно будет идти наполнение буффера без угрозы дедлока, отдельно - выполнение запросов на удаление и ретраи

В for-select, как я это вижу, можно сделать это следующим образом:
```go
flushTick := time.NewTicker(flushAfter)
flushCh := make(chan struct{}, 10) // делаем сигнальный канал буфферизированным на всякий случай

go func() {
    for range flushCh {
        if err := w.flushBuf(); err != nil {
            time.Sleep(retryIn)
            flushCh <- struct{}{}
        }
    }
}()

for {
    select {
    case v := <-w.inCh:
        // добавить новую задачу в буффер, если буффер заполнился посылаем "сигнал" на его очистку
    case <-flushTick.C:
        // посылаем "сигнал" на очистку буфера
    case <-ctx.Done():
        // завершаем работу воркера
    }
}

2023-02-21 08:13 UTC, Barugoo commented on internal/service/delete_worker.go
> +		log.Println("URL ids to delete flushing error", err)
Тут нам тоже надо бы ошибку возвращать и логгировать уже там, где вызывается `flushAll`

2023-02-21 08:14 UTC, Barugoo requested changes
Отлично, есть предложение как можно улучшить логику delete worker, посмотри пожалуйтса

2023-02-23 10:26 UTC, MalyginaEkaterina commented
Код с дополнительной горутиной получился сложным и все равно есть возможность блокировок из-за мьютекса.
Так же есть потенциальная возможность переполнения памяти из-за бесконечно растущего буфера.
Согласна, что в предыдущем решении нельзя было оставить заблокированными пользователей. Думаю, что неплохим решением было бы просто возвращать им ошибку и не принимать на удаление в  случае, если есть проблемы с БД, например, в данный момент, т.е. просто поправить этот метод:
`func (w *DeleteURL) Delete(ids []internal.IDToDelete) error {
	for _, v := range ids {
		select {
		case w.inCh <- v: 
		default: return ErrDeletion
		}
	}
	return nil
}`

2023-02-27 23:32 UTC, Barugoo commented on internal/service/delete_worker.go
> +			}()
Я так понимаю анонимная функция здесь обьвляется исключительно ради `defer`. Если так то кажется проще сделать работу с мьютексом без дефер:
```go
	for {
 		select {
 		case v := <-w.inCh:
 			w.mutex.Lock()
 			w.buf = append(w.buf, v)
                            
 			if len(w.buf) >= deleteChunkSize {
 				flushSignal.Notify()
 			}
                        w.mutex.Unlock()
                case <-flushTick.C:

2023-02-27 23:42 UTC, Barugoo commented on internal/service/delete_worker.go
> +		case <-flushTick.C:
Кстати наверное правильнее было бы сбрасывать тикер после каждого flush по сигналу из канала flushSignal.C, чтобы уменьшить количество ненужных флашей. Вариант с тикером у нас по идее - это фоллбэк который позволяет прогонять удаления даже если буфер не успевает заполнится (чтобы слишком долго задачки в буфере не висели). 
Но основная логика у нас это именно заполнение буффера - если оно итак просходит регулярно, то тогда тикер будет триггерить флаши которые нам в общем-то и не нужны.
Соответствено сделать это можно было бы так:
```go
if len(w.buf) >= deleteChunkSize {
    flushSignal.Notify()
    flushTick = time.NewTicker(flushAfter)
}

2023-02-27 23:43 UTC, Barugoo approved these changes
Отлично!

2023-03-29 11:20 UTC, merged