Iter17
MalyginaEkaterina/shortener pull request #17
Opened 2023-04-01 22:22 UTC by MalyginaEkaterina

2023-04-05 22:52 UTC, Barugoo commented on internal/handlers/auth_test.go
> +func BenchmarkCheckSign(b *testing.B) {
Обычно мы пишем бенчмарки для того чтобы сравнить две реализации одной и той же штуки, бенчмарк в вакууме нам никакой особо полезной информации не дает.

Но тк у нас реализация целиком состоит из либ стандартной библиотеки сторонних аналогов которых я не нашол (мб плохо искал), то особо не посравниваешь, так что давай оставим как есть

2023-04-05 22:55 UTC, Barugoo commented on internal/handlers/example_test.go
> +func Example() {
Давай побьем эту функцию по хэндлерам, а-ля:
```go
Example_ShortenURL()
Example_GetOriginalURL()
//...
```

Еще момент - одна из главных фишек примеров которые генерит go doc из этих функций - это возможность выполнять код прямо в документации. Текущая реализация делать нам это непозволяет, тк нужен запущенный сервер на локалхосте. Давай заменим реальный сервер на тестовый из либы `httptest`, чтобы можно было этот код выполнять без каких-либо дополнительных условий

Чото подобное здесь можно увидеть:
https://sourcegraph.com/github.com/golang/go/-/blob/src/net/http/httptest/example_test.go

2023-04-05 22:57 UTC, Barugoo commented on internal/storage/memory_storage_test.go
> +	store := NewMemoryStorage()
Опять же, тут было бы полезнее сравнивать две разных реализации хранилки. Можем это делать в одной функции, просто разбей ее на подбенчмарки через b.Run

Соответственно было бы неплохо сравнить реализацию хранилки в памяти и в файле - нужно будет дописать несколько строк

2023-04-05 22:57 UTC, Barugoo requested changes
Хорошо, есть комментарии
Спасибо что подождала ревью

2023-04-09 10:07 UTC, MalyginaEkaterina commented on internal/handlers/example_test.go
> +func Example() {
Использовать сервер из httptest не получилось, т.к. неизвестен порт заранее и для корректной работы с BaseURL потребовалось бы менять остальной код.

2023-04-10 21:39 UTC, Barugoo commented on internal/handlers/example_test.go
> +func Example() {
@MalyginaEkaterina так там же можно получить адрес тестового сервера, вот тута
https://sourcegraph.com/github.com/golang/go/-/blob/src/net/http/httptest/example_test.go?L43

2023-04-11 15:29 UTC, merged